### ISSUE TITLE
Cannot change to pull: No such file or directory

### ISSUE THREAD

**Issue by brilovescoding** [jfiksel/github-classroom-for-teachers#2]
Hello,

I was able to successfully clone and download a large set of repositories for my students' first assignment. I didn't bother to push any commits afterwards. Now today I am trying to clone another set of labs but am getting the error I indicated above. Here is my console output:

> brianmacbook:mass_clone admin$ ./clone_all_helper_example.sh apcs-lab-2-input
> Using ssh
> Enter Github Password:
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.30.253.117...
> * TCP_NODELAY set
> * Connected to api.github.com (192.30.253.117) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/cert.pem
>   CApath: none
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> } [512 bytes data]
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> { [108 bytes data]
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> { [3091 bytes data]
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> { [333 bytes data]
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> { [4 bytes data]
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> } [70 bytes data]
> * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> } [1 bytes data]
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> } [16 bytes data]
> * TLSv1.2 (IN), TLS change cipher, Client hello (1):
> { [1 bytes data]
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> { [16 bytes data]
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> * ALPN, server accepted to use http/1.1
> * Server certificate:
> *  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
> *  start date: Jan 18 00:00:00 2017 GMT
> *  expire date: Apr 17 12:00:00 2020 GMT
> *  subjectAltName: host "api.github.com" matched cert's "*.github.com"
> *  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
> *  SSL certificate verify ok.
> * Server auth using Basic with user 'brianjschott'
> > GET /orgs/bronxacademy/repos?per_page=100 HTTP/1.1
> > Host: api.github.com
> > Authorization: Basic YnJpYW5qc2Nob3R0OjAxMTVEOGM0IQ==
> > User-Agent: curl/7.54.0
> > Accept: */*
> >
> < HTTP/1.1 200 OK
> < Server: GitHub.com
> < Date: Mon, 16 Oct 2017 00:57:24 GMT
> < Content-Type: application/json; charset=utf-8
> < Content-Length: 698135
> < Status: 200 OK
> < X-RateLimit-Limit: 5000
> < X-RateLimit-Remaining: 4880
> < X-RateLimit-Reset: 1508118014
> < Cache-Control: private, max-age=60, s-maxage=60
> < Vary: Accept, Authorization, Cookie, X-GitHub-OTP
> < ETag: "b491c2656f919e9d59b9928781b4d99e"
> < X-GitHub-Media-Type: github.v3; format=json
> < Link: <https://api.github.com/organizations/14323329/repos?per_page=100&page=2>; rel="next", <https://api.github.com/organizations/14323329/repos?per_page=100&page=3>; rel="last"
> < Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
> < Access-Control-Allow-Origin: *
> < Content-Security-Policy: default-src 'none'
> < Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
> < X-Content-Type-Options: nosniff
> < X-Frame-Options: deny
> < X-XSS-Protection: 1; mode=block
> < X-Runtime-rack: 0.353002
> < X-GitHub-Request-Id: E437:128EA:154A78C:383B86E:59E403F4
> <
> { [256 bytes data]
> 100  681k  100  681k    0     0   644k      0  0:00:01  0:00:01 --:--:--  644k
> * Connection #0 to host api.github.com left intact
> usage: basename string [suffix]
>        basename [-a] [-s suffix] string [...]
> fatal: Cannot change to 'pull': No such file or directory

**Comment by jfiksel** [comment]
I am not sure what the error is here, it's hard for me to debug these types of errors since they are difficult to reproduce.

**Comment by gbajaj20** [comment]
Hi, I am getting the same error while I try to mass clone student repositories to my local. Any resolution on this yet?

**Comment by jfiksel** [comment]
The only suggestion I can think of is to [create a personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) and to try using this instead of your password. Given that this does not seem to be a common problem, I do not think that this seems to be an issue with the shell script.

**Comment by gbajaj20** [comment]
Makes sense. I'll give it a try. Thanks, Jacob.

**Comment by lrjager** [comment]
Just commenting to say I had this same error, and the personal access token fixed it for me.

**Comment by hardin47** [comment]
the problem is likely in the buttons you need to select when creating your PAT.  go back and make sure that when you created your PAT you gave yourself appropriate permissions.  make sure you've selected all of these (and feel free to select the much longer set of boxes, it won't hurt!):

![image](https://user-images.githubusercontent.com/7210585/150700159-f6baccf7-8a99-496f-9e3a-9157be8e82cf.png)

**Comment by memm74** [comment]
I'm using a PAT with all the rigth boxes ticked and still get the same error (using Windows Git Bash).
