### ISSUE TITLE
Step 4 Clarification - 

### ISSUE THREAD

**Issue by kmkinnaird** [jfiksel/github-classroom-for-teachers#5]
I'm at step 4 of the classroom step up:

> Go to the current year's version of the classroom organization. Under settings, go to member privileges. Change Default repository permission to "none" (if it's not already) and save these changes. This will make it so that students cannot change non-assignment repositories in the organization.

Do you mean "Base Permissions"?
<img width="1079" alt="GitHubClassroomStep5" src="https://user-images.githubusercontent.com/9118586/63115512-52025f00-bf65-11e9-9318-1c993238fb30.png">

**Comment by jfiksel** [comment]
Yes, I will make that change. Thanks for letting me know!
